// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdate) SetTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *PaymentOrderUpdate) ClearTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetAmountUsd sets the "amount_usd" field.
func (_u *PaymentOrderUpdate) SetAmountUsd(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmountUsd()
	_u.mutation.SetAmountUsd(v)
	return _u
}

// SetNillableAmountUsd sets the "amount_usd" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountUsd(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountUsd(*v)
	}
	return _u
}

// AddAmountUsd adds value to the "amount_usd" field.
func (_u *PaymentOrderUpdate) AddAmountUsd(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmountUsd(v)
	return _u
}

// SetAmountRmb sets the "amount_rmb" field.
func (_u *PaymentOrderUpdate) SetAmountRmb(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmountRmb()
	_u.mutation.SetAmountRmb(v)
	return _u
}

// SetNillableAmountRmb sets the "amount_rmb" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountRmb(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountRmb(*v)
	}
	return _u
}

// AddAmountRmb adds value to the "amount_rmb" field.
func (_u *PaymentOrderUpdate) AddAmountRmb(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmountRmb(v)
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *PaymentOrderUpdate) SetExchangeRate(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableExchangeRate(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *PaymentOrderUpdate) AddExchangeRate(v float64) *PaymentOrderUpdate {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *PaymentOrderUpdate) SetPayType(v string) *PaymentOrderUpdate {
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePayType(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *PaymentOrderUpdate) ClearPayType() *PaymentOrderUpdate {
	_u.mutation.ClearPayType()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayType(); ok {
		if err := paymentorder.PayTypeValidator(v); err != nil {
			return &ValidationError{Name: "pay_type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.pay_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(paymentorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AmountUsd(); ok {
		_spec.SetField(paymentorder.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountUsd(); ok {
		_spec.AddField(paymentorder.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountRmb(); ok {
		_spec.SetField(paymentorder.FieldAmountRmb, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountRmb(); ok {
		_spec.AddField(paymentorder.FieldAmountRmb, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(paymentorder.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(paymentorder.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(paymentorder.FieldPayType, field.TypeString, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(paymentorder.FieldPayType, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdateOne) SetTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetAmountUsd sets the "amount_usd" field.
func (_u *PaymentOrderUpdateOne) SetAmountUsd(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountUsd()
	_u.mutation.SetAmountUsd(v)
	return _u
}

// SetNillableAmountUsd sets the "amount_usd" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountUsd(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountUsd(*v)
	}
	return _u
}

// AddAmountUsd adds value to the "amount_usd" field.
func (_u *PaymentOrderUpdateOne) AddAmountUsd(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountUsd(v)
	return _u
}

// SetAmountRmb sets the "amount_rmb" field.
func (_u *PaymentOrderUpdateOne) SetAmountRmb(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountRmb()
	_u.mutation.SetAmountRmb(v)
	return _u
}

// SetNillableAmountRmb sets the "amount_rmb" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountRmb(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountRmb(*v)
	}
	return _u
}

// AddAmountRmb adds value to the "amount_rmb" field.
func (_u *PaymentOrderUpdateOne) AddAmountRmb(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountRmb(v)
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *PaymentOrderUpdateOne) SetExchangeRate(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableExchangeRate(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *PaymentOrderUpdateOne) AddExchangeRate(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *PaymentOrderUpdateOne) SetPayType(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePayType(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *PaymentOrderUpdateOne) ClearPayType() *PaymentOrderUpdateOne {
	_u.mutation.ClearPayType()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayType(); ok {
		if err := paymentorder.PayTypeValidator(v); err != nil {
			return &ValidationError{Name: "pay_type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.pay_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(paymentorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AmountUsd(); ok {
		_spec.SetField(paymentorder.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountUsd(); ok {
		_spec.AddField(paymentorder.FieldAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountRmb(); ok {
		_spec.SetField(paymentorder.FieldAmountRmb, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountRmb(); ok {
		_spec.AddField(paymentorder.FieldAmountRmb, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(paymentorder.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(paymentorder.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(paymentorder.FieldPayType, field.TypeString, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(paymentorder.FieldPayType, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
